services:
  readora-node:
    container_name: readora-backend-node
    build: .
    ports:
      - ${APP_PORT}
    environment:
      - APP_ENV=production
      - APP_PORT=4001
    env_file:
      - .env
    networks:
      - readora-network

networks:
  readora-network:
    external: true
